version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: financial-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - financial-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: financial-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - financial-net

  postgres-dev:
    image: postgres:15
    container_name: financial-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres87
      POSTGRES_PASSWORD: postgres8725
      POSTGRES_DB: findb
    ports:
      - "5432:5432"
    volumes:
      - dev_data:/var/lib/postgresql/data
    networks:
      - financial-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: financial-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres-dev
    networks:
      - financial-net

  postgres-qa:
    image: postgres:15
    container_name: financial-db-qa
    restart: always
    environment:
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_pass
      POSTGRES_DB: findb_qa
    ports:
      - "5433:5432"
    volumes:
      - qa_data:/var/lib/postgresql/data
    networks:
      - financial-net

  postgres-prod:
    image: postgres:15
    container_name: financial-db-prod
    restart: always
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_secret
      POSTGRES_DB: financial_prod
    ports:
      - "5434:5432"
    volumes:
      - prod_data:/var/lib/postgresql/data
    networks:
      - financial-net

networks:
  financial-net:
    driver: bridge

volumes:
  dev_data:
  qa_data:
  prod_data:
