spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/findb
    username: postgres87
    password: postgres8725

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:5432/findb
    user: postgres87
    password: postgres8725