spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/findb
    username: postgres87
    password: postgres8725
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:5432/findb
    user: postgres87
    password: postgres8725

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: financeiro-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      ack-mode: manual

server:
  port: 8080