spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/findb
    username: postgres87
    password: postgres8725
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:5432/findb
    user: postgres87
    password: postgres8725

server:
  port: 8080